---

- name: Upgrade Packages
  hosts: servers2
  vars:
  gather_facts: True
  become: True
  tasks:

  - name: Upgrade all packages to the latest version
    dnf:
      name: "*"
      state: latest
