---
- name: Start of jinja2 template push
  hosts: testing
  vars:
  gather_facts: True
  become: False
  tasks: 

    - name: Get information on all hosts 
      shell: uptime
      register: uptime

    - name: Copy template to all hosts
      template:
        src: /home/ansible/playbooks/template-all.j2
        dest: "/home/ansible/playbooks/report.{{ansible_date_time.iso8601_basic_short}}.txt"
      run_once: yes
      delegate_to: localhost
